name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: '0 0 * * *'  # Exécute l'action une fois par jour à minuit
  workflow_dispatch:  # Permet de lancer manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: ${{ github.repository_owner }}